logging:
  level:
    # 这里设置的日志级别优先于log4j2.xml文件Loggers中的日志级别。
    com.orangeforms: info

server:
  port: 9000

application:
  # 缺省的文件上传根目录。
  uploadFileBaseDir: ./zz-resource/upload-files/upms
  # 初始化密码。
  defaultUserPassword: 123456
  # 每个微服务的url目录上下文，如(/admin/upms)，通常和网关的路由path一致。
  serviceContextPath: /admin/upms
  # 是否忽略远程调用中出现的任何错误，包括逻辑异常和系统异常。
  # 通常在调试和测试阶段设置为false，以便及时发现问题。
  ignoreRpcError: false
  # Session的数据权限信息在Redis中的过期时间(秒)。
  dataPermExpiredSeconds: 86460

datafilter:
  tenant:
    enabled: false
  dataperm:
    enabled: true
    # 在拼接数据权限过滤的SQL时，我们会用到sys_dept_relation表，该表的前缀由此配置项指定。
    # 如果没有前缀，请使用 "" 。
    deptRelationTablePrefix: zz_

sequence:
  # 是否使用基于美团Leaf的分布式Id生成器。
  advanceIdGenerator: true
  # 多个zk服务之间逗号分隔。
  zkAddress: localhost:2181
  # 与本机的ip一起构成zk中标识不同服务实例的key值。
  idPort: 19000
  # zk中生成WorkNode的路径。不同的业务可以使用不同的路径，以免冲突。
  zkPath: com/orangeforms

common-log:
  # 操作日志配置，对应配置文件common-log/OperationLogProperties.java
  operation-log:
    enabled: true
    kafkaTopic: SysOperationLog

mybatis-plus:
  mapper-locations: classpath:com/orangeforms/*/dao/mapper/*Mapper.xml,com/orangeforms/common/datasync/dao/mapper/*Mapper.xml,com/orangeforms/common/log/dao/mapper/*Mapper.xml
  type-aliases-package: com.orangeforms.*.model,com.orangeforms.common.datasync.model,com.orangeforms.common.log.model
  global-config:
    db-config:
      logic-delete-value: -1
      logic-not-delete-value: 1

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: false
  params: count=countSql

aj:
  captcha:
    # 缓存local/redis..
    cache-type: redis
    # 验证码类型default两种都实例化。
    type: default
    # 右下角水印文字(我的水印)
    water-mark: 我的水印
    #点选字体样式 默认Font.BOLD
    font-style: 1
    #点选字体字体大小
    font-size: 25
    # 支持项目路径,以classpath:开头,取resource目录下路径,例：classpath:images/jigsaw
    jigsaw: classpath:images/jigsaw
    # 支持项目路径,以classpath:开头,取resource目录下路径,例：classpath:images/pic-click
    pic-click: classpath:images/pic-click
    history-data-clear-enable: false
    # 接口请求次数一分钟限制是否开启 true|false
    req-frequency-limit-enable: false
    # 验证失败5次，get接口锁定
    req-get-lock-limit: 5
    # 验证失败后，锁定时间间隔,s
    req-get-lock-seconds: 360
    # get接口一分钟内请求数限制
    req-get-minute-limit: 30
    # check接口一分钟内请求数限制
    req-check-minute-limit: 30
    # verify接口一分钟内请求数限制
    req-verify-minute-limit: 60
    # 校验滑动拼图允许误差偏移量(默认5像素)
    slip-offset: 5
    # aes加密坐标开启或者禁用(true|false)
    aes-status: true
    # 滑动干扰项(0/1/2)
    interference-options: 2

spring:
  # aj-captcha 对redis缓存的依赖。
  redis:
    database: 2
    host: localhost
    port: 6379
    password: ''
    timeout: 60000
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      batch-size: 16
      retries: 0
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      main:
        url: jdbc:mysql://localhost:3306/zzdemo-multi?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      operation-log:
        url: jdbc:mysql://localhost:3306/zzdemo-multi?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: upms
      initialSize: 10
      minIdle: 10
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat,wall
      useGlobalDataSourceStat: true
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*,/actuator/*"
      stat-view-servlet:
        enabled: true
        urlPattern: /druid/*
        resetEnable: true
