// ---Auto Generated by Only4Play ---
package com.shooterj.sys.domain.template.objecttemplate.repository;


import com.shooterj.jpa.support.BaseRepository;
import com.shooterj.sys.domain.template.objecttemplate.TemplateCategory;

public interface TemplateCategoryRepository extends BaseRepository<TemplateCategory, Long> {
}
