// ---Auto Generated by shooterj ---
package com.shooterj.sys.domain.template.objecttemplate.query;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class ObjectTemplateQuery extends BaseObjectTemplateQuery {
}
