// ---Auto Generated by shooterj ---
package com.shooterj.sys.domain.template.objecttemplate.vo;

import com.shooterj.sys.domain.template.objecttemplate.ObjectTemplate;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class ObjectTemplateVO extends BaseObjectTemplateVO {
  public ObjectTemplateVO() {
  }

  public ObjectTemplateVO(ObjectTemplate source) {
    super(source);
  }
}
