// ---Auto Generated by shooterj ---
package com.shooterj.sys.domain.template.objecttemplate.updater;

import com.shooterj.sys.domain.template.objecttemplate.ObjectTemplate;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Long;
import java.lang.String;
import java.util.Optional;
import lombok.Data;

@Schema
@Data
public class BaseObjectTemplateUpdater {
  @Schema(
      title = "模板名称"
  )
  private String name;

  @Schema(
      title = "模板编码"
  )
  private String code;

  @Schema(
      title = "创建人"
  )
  private String createUser;

  @Schema(
      title = "模板code"
  )
  private String categoryCode;

  @Schema(
      title = "模板id"
  )
  private Long categoryId;

  @Schema(
      title = "描述信息"
  )
  private String description;

  private Long id;

  protected BaseObjectTemplateUpdater() {
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public String getCreateUser() {
    return createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  public String getCategoryCode() {
    return categoryCode;
  }

  public void setCategoryCode(String categoryCode) {
    this.categoryCode = categoryCode;
  }

  public Long getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(Long categoryId) {
    this.categoryId = categoryId;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public void updateObjectTemplate(ObjectTemplate param) {
    Optional.ofNullable(getName()).ifPresent(v -> param.setName(v));
    Optional.ofNullable(getCode()).ifPresent(v -> param.setCode(v));
    Optional.ofNullable(getCreateUser()).ifPresent(v -> param.setCreateUser(v));
    Optional.ofNullable(getCategoryCode()).ifPresent(v -> param.setCategoryCode(v));
    Optional.ofNullable(getCategoryId()).ifPresent(v -> param.setCategoryId(v));
    Optional.ofNullable(getDescription()).ifPresent(v -> param.setDescription(v));
  }

  public Long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }
}
