// ---Auto Generated by shooterj ---
package com.shooterj.sys.domain.template.objecttemplate.updater;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class ObjectTemplateUpdater extends BaseObjectTemplateUpdater {
}
